### ISSUE TITLE
Document the workflow

### ISSUE THREAD

**Issue by sven-frotscher** [KaTeX/katex-fonts#80]
Prompted by a conversation under KaTeX/KaTeX#2284:

* Which files should be edited prior to running `buildFonts.sh`? 
* Where are the TeX files which src/fonts/makeFF supposedly uses?
  * Alternatively: What should they contain and where should they be placed?

`README.md` and `CONTRIBUTING.md` don't make that clear.

**Comment by edemaine** [comment]
Copying from the previous conversation:

> Generally you change the following files:
> * `src/fonts/OTF/TeX/makeFF`
> * `src/metrics/mapping.pl`

Regarding "where's the TeX", I believe the answer is in the line `texlive \` in the `Dockerfile`, which installs the Ubuntu `texlive` package, which includes fonts.  Reading `src/fonts/Makefile`, it looks like gets processed somewhat directly by `mftrace` which is another Ubuntu package, which produces `.pfa` files, which then get used/included in `makeFF`. Does that clarify?

**Comment by sven-frotscher** [comment]
If I understand correctly:
* `texlive` provides TeX fonts in MAKEFONT (pixel graphics) format
* `mftrace` traces (vectorizes) them
* The configuration for `mftrace` lies in `src/fonts/Makefile` and `src/fonts/makeFF`

Is that correct? If so, that could be clarified, e.g. in `README.md`.
And is there a way to bypass the MAKEFONT way and use an OTF source directly (e.g. to import glyphs from [`stix2-otf`](https://www.ctan.org/pkg/stix2-otf))?

**Comment by edemaine** [comment]
I think you mean "METAFONT" instead of "MAKEFONT". METAFONT is actually a vector language (by Knuth too), so there's no need to bitmap and then trace like we're currently doing. The old issue #19 proposes a way to do just this. I agree that it would be great to do.

I would presume there's a way to convert OTF/TTF fonts to PFA which is what we're getting from `mftrace`, or otherwise hook into the rest of the processing chain.  But generalizing to fonts other than Computer Modern is a much bigger project that I'm not sure is the most pressing need for KaTeX (or this repo) at the moment.

**Comment by sven-frotscher** [comment]
Yes, I meant METAFONT.
Being restricted to it might not be such a big deal in the long run if the way via pixels and `potrace` isn't necessary.
There _are_ other METAFONTs than Computer Modern in `texlive` and some could add certain glyphs (e.g. the ones I requested in #78) to the KaTeX fonts. Using those probably wouldn't mean changing the way the glyphs are processed. However, then consensus would need to be reached on which font to select in some cases :thinking:

**Comment by edemaine** [comment]
Yes, we don't want to add just any font, and will have to make some choices for overlapping symbols, but hopefully we can stick to popular packages like `stix` (in the case of #78).
